Importing The Libraries Required

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
print('Yes')

Yes


#**Data pre processing step**
#**Training Data**

In [3]:
data_train = pd.read_csv('sign_mnist_train.csv')
print(data_train.head())
data_train=np.array(data_train)
m, n = data_train.shape
np.random.shuffle(data_train)
data_train=data_train.T
print(data_train[:5])
Y_train=data_train[0]
X_train=data_train[1:n]
X_train=X_train/255

   label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      3     107     118     127     134     139     143     146     150   
1      6     155     157     156     156     156     157     156     158   
2      2     187     188     188     187     187     186     187     188   
3      2     211     211     212     212     211     210     211     210   
4     13     164     167     170     172     176     179     180     184   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0     153  ...       207       207       207       207       206       206   
1     158  ...        69       149       128        87        94       163   
2     187  ...       202       201       200       199       198       199   
3     210  ...       235       234       233       231       230       226   
4     185  ...        92       105       105       108       133       163   

   pixel781  pixel782  pixel783  pixel784  
0       206       204       20

#Testing Data

In [4]:
data_test = pd.read_csv('sign_mnist_test.csv')
print(data_test.head())
data_test=np.array(data_test)
i,j= data_test.shape
np.random.shuffle(data_test)
data_test=data_test.T
print(data_test[:5])
Y_test=data_test[0]
X_test=data_test[1:j]
X_test=X_test/255



   label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      6     149     149     150     150     150     151     151     150   
1      5     126     128     131     132     133     134     135     135   
2     10      85      88      92      96     105     123     135     143   
3      0     203     205     207     206     207     209     210     209   
4      3     188     191     193     195     199     201     202     203   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0     151  ...       138       148       127        89        82        96   
1     136  ...        47       104       194       183       186       184   
2     147  ...        68       166       242       227       230       227   
3     210  ...       154       248       247       248       253       236   
4     203  ...        26        40        64        48        29        46   

   pixel781  pixel782  pixel783  pixel784  
0       106       112       12

Desgining The algorithm 
All the Steps required for Gradient descent Algorithm

In [5]:
#inliatlizing the varaibles
def init_params():
    W1 = np.random.rand(64, 784) - 0.5
    b1 = np.random.rand(64, 1) - 0.5
    W2 = np.random.rand(25, 64) - 0.5
    b2 = np.random.rand(25, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)
# function to convert the Numbers Into bayesian stats
def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
# calculating the values using Matrix Multiplication
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2
# Non Linearity Function
def ReLU_deriv(Z):
    return Z > 0
#Probability Matrix
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, 25))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y
# finding the error betweem the true value and predicted value
def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2,axis=1, keepdims=True)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1 ,axis=1, keepdims=True)
    return dW1, db1, dW2, db2
# Updating the Values of the varaiables
def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [6]:
# returning the predictions
def get_predictions(A2):
    return np.argmax(A2, 0)
# getting the accuracy 
def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size
# making the steps in the Chornological order
def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 5000)

Iteration:  0
[13 19  1 ... 19 19 19] [12 21 24 ... 23 11  8]
0.04600254962666181
Iteration:  10
[17 13  7 ... 13 13 13] [12 21 24 ... 23 11  8]
0.05361500637406665
Iteration:  20
[13 13 16 ... 13 13 13] [12 21 24 ... 23 11  8]
0.06283008559460936
Iteration:  30
[13 13 16 ... 13 13 13] [12 21 24 ... 23 11  8]
0.07969404480058277
Iteration:  40
[13 17  1 ... 13 16 16] [12 21 24 ... 23 11  8]
0.09582953924603897
Iteration:  50
[12 17  1 ... 13 16 16] [12 21 24 ... 23 11  8]
0.10730285922418503
Iteration:  60
[ 6 17  1 ... 13 24 16] [12 21 24 ... 23 11  8]
0.1203423784374431
Iteration:  70
[ 6 17  1 ... 13 14 16] [12 21 24 ... 23 11  8]
0.13742487707157167
Iteration:  80
[ 6  3  1 ... 17  8 15] [12 21 24 ... 23 11  8]
0.14583864505554545
Iteration:  90
[ 6  3  1 ... 17  8  3] [12 21 24 ... 23 11  8]
0.15479876160990713
Iteration:  100
[ 6  3  1 ... 17  8  3] [12 21 24 ... 23 11  8]
0.161354944454562
Iteration:  110
[ 6  3  1 ... 17  8  3] [12 21 24 ... 23 11  8]
0.17129848843562193
Iterat

KeyboardInterrupt: 

In [ ]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_test[:, index, None]
    prediction = make_predictions(X_test[:, index, None], W1, b1, W2, b2)
    label = Y_test[index]
    
    # The Alphabet Map (0=A, 1=B...)
    # Note: This dataset skips J (9) because it involves motion.
    # If your dataset maps 0->A directly, this works. 
    letters = "ABCDEFGHIKLMNOPQRSTUVWXY" # 24 letters (skipping J and Z)
    
    print("Prediction: ", prediction[0])
    print("True Label: ", label)
    
    # Try to convert to letter if possible
    if label < len(letters):
        print(f"Model says: {letters[prediction[0]]}")
        print(f"Actual is:  {letters[label]}")
        
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()

# Run this line to see a random example!
# Change the number '5' to any number between 0 and the size of your test set
test_prediction(5, W1, b1, W2, b2)